name: Push changes workflow
on:
  push:
    branches:
      - "feat/*"

jobs:
  run_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      working-dir: ./
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        working-directory: ${{env.working-dir}}
        run: |
          yarn

      - name: test
        working-directory: ${{env.working-dir}}
        run: |
          yarn test

  run_contentful_push:
    name: "Push contentful changes "
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - uses: actions/checkout@v2
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create env file
        run: |
          touch .env
          echo CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }} >> .env
          echo CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_MANAGEMENT_API_KEY }} >> .env
          echo CONTENTFUL_ENVIONMENT_ID="master" >> .env

          cat .env

      - name: install dependencies
        working-directory: ${{env.working-dir}}
        run: |
          yarn

      - name: "contentful push"
        run: |
          yarn contentful:push
