name: Push changes workflow
on:
  push:
    branches:
      - "feat/*"

jobs:
  run_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      working-dir: ./
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        working-directory: ${{env.working-dir}}
        run: |
          yarn

      - name: test
        working-directory: ${{env.working-dir}}
        run: |
          yarn test

  run_contentful_push:
    name: "Push contentful changes "
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - id: "test2"
        run: |
          echo " running contentful push"
